# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1338ac2c544de1a42b4de205b1fcf5df0ed1655e88ef4c2df89f8b0b11aaccf57a1399412391044d517aaf724dcb4433c6692785707fa3f9def3781a869bc646

test:
  secret_key_base: 90f9ea89ec640ca6d9e83892d1c7758c821dc21b4bc8b24a3eb3490fdd4a214623c90c647eb849040751241f335172ea44c0445a7c3f02b0bb23b3172e50eefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
